{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "inqqvrre7ly2b"
  },
  "info": {
    "title": "RimSys Eval",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "summary": "User Index",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "data": [
                        {
                          "id": 1,
                          "name": "Admin",
                          "email": "admin@admin.com",
                          "last_login_at": "2022-11-28 05:30:05",
                          "created_at": "2022-11-28T05:29:41.000000Z",
                          "updated_at": "2022-11-28T05:30:05.000000Z"
                        },
                        {
                          "id": 2,
                          "name": "Joshuah Quitzon",
                          "email": "marcos.kuhic@example.org",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 3,
                          "name": "Prof. Geoffrey Hansen",
                          "email": "roxane86@example.net",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 4,
                          "name": "Giovanna Legros PhD",
                          "email": "stella.walker@example.net",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 5,
                          "name": "Brown Barton",
                          "email": "kfay@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 6,
                          "name": "Lorenza Marvin",
                          "email": "hailey.cronin@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 7,
                          "name": "Ms. Alexandrine Weber",
                          "email": "owisoky@example.org",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 8,
                          "name": "Sadie Yundt",
                          "email": "wpredovic@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 9,
                          "name": "Isobel Medhurst",
                          "email": "wilber.parker@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 10,
                          "name": "Prof. Keagan Spencer V",
                          "email": "schamberger.bridgette@example.net",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 11,
                          "name": "Miss Claudie Toy III",
                          "email": "bosco.elody@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        }
                      ],
                      "links": {
                        "first": "http://rimsys.test/api/users?page=1",
                        "last": "http://rimsys.test/api/users?page=1",
                        "prev": null,
                        "next": null
                      },
                      "meta": {
                        "current_page": 1,
                        "from": 1,
                        "last_page": 1,
                        "links": [
                          {
                            "url": null,
                            "label": "&laquo; Previous",
                            "active": false
                          },
                          {
                            "url": "http://rimsys.test/api/users?page=1",
                            "label": "1",
                            "active": true
                          },
                          {
                            "url": null,
                            "label": "Next &raquo;",
                            "active": false
                          }
                        ],
                        "path": "http://rimsys.test/api/users",
                        "per_page": 15,
                        "to": 11,
                        "total": 11
                      }
                    }
                  },
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "last_login_at": {
                            "type": [
                              "null",
                              "string"
                            ]
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "links": {
                      "type": "object",
                      "properties": {
                        "first": {
                          "type": "string"
                        },
                        "last": {
                          "type": "string"
                        },
                        "prev": {
                          "type": "null"
                        },
                        "next": {
                          "type": "null"
                        }
                      }
                    },
                    "meta": {
                      "type": "object",
                      "properties": {
                        "current_page": {
                          "type": "integer"
                        },
                        "from": {
                          "type": "integer"
                        },
                        "last_page": {
                          "type": "integer"
                        },
                        "links": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "url": {
                                "type": [
                                  "null",
                                  "string"
                                ]
                              },
                              "label": {
                                "type": "string"
                              },
                              "active": {
                                "type": "boolean"
                              }
                            }
                          }
                        },
                        "path": {
                          "type": "string"
                        },
                        "per_page": {
                          "type": "integer"
                        },
                        "to": {
                          "type": "integer"
                        },
                        "total": {
                          "type": "integer"
                        }
                      }
                    },
                    "": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "data": [
                        {
                          "id": 1,
                          "name": "Admin",
                          "email": "admin@admin.com",
                          "last_login_at": "2022-11-28 05:30:05",
                          "created_at": "2022-11-28T05:29:41.000000Z",
                          "updated_at": "2022-11-28T05:30:05.000000Z"
                        },
                        {
                          "id": 2,
                          "name": "Joshuah Quitzon",
                          "email": "marcos.kuhic@example.org",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 3,
                          "name": "Prof. Geoffrey Hansen",
                          "email": "roxane86@example.net",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 4,
                          "name": "Giovanna Legros PhD",
                          "email": "stella.walker@example.net",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 5,
                          "name": "Brown Barton",
                          "email": "kfay@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 6,
                          "name": "Lorenza Marvin",
                          "email": "hailey.cronin@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 7,
                          "name": "Ms. Alexandrine Weber",
                          "email": "owisoky@example.org",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 8,
                          "name": "Sadie Yundt",
                          "email": "wpredovic@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 9,
                          "name": "Isobel Medhurst",
                          "email": "wilber.parker@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 10,
                          "name": "Prof. Keagan Spencer V",
                          "email": "schamberger.bridgette@example.net",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        },
                        {
                          "id": 11,
                          "name": "Miss Claudie Toy III",
                          "email": "bosco.elody@example.com",
                          "last_login_at": null,
                          "created_at": "2022-11-28T05:29:42.000000Z",
                          "updated_at": "2022-11-28T05:29:42.000000Z"
                        }
                      ],
                      "links": {
                        "first": "http://rimsys.test/api/users?page=1",
                        "last": "http://rimsys.test/api/users?page=1",
                        "prev": null,
                        "next": null
                      },
                      "meta": {
                        "current_page": 1,
                        "from": 1,
                        "last_page": 1,
                        "links": [
                          {
                            "url": null,
                            "label": "&laquo; Previous",
                            "active": false
                          },
                          {
                            "url": "http://rimsys.test/api/users?page=1",
                            "label": "1",
                            "active": true
                          },
                          {
                            "url": null,
                            "label": "Next &raquo;",
                            "active": false
                          }
                        ],
                        "path": "http://rimsys.test/api/users",
                        "per_page": 15,
                        "to": 11,
                        "total": 11
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-users",
        "description": "",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header"
          }
        ]
      }
    },
    "/users/{userId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "exclusiveMinimum": true,
            "minimum": 1,
            "example": 1
          },
          "name": "userId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "User Show",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "last_login_at": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "data": {
                        "id": 0,
                        "name": "string",
                        "email": "string",
                        "last_login_at": "string",
                        "created_at": "string",
                        "updated_at": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-users-userId",
        "description": ""
      },
      "post": {
        "summary": "User Store",
        "operationId": "post-users-userId",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "last_login_at": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "data": {
                        "id": 1,
                        "name": "Admin",
                        "email": "admin@admin.com",
                        "last_login_at": "2022-11-28 05:30:05",
                        "created_at": "2022-11-28T05:29:41.000000Z",
                        "updated_at": "2022-11-28T05:30:05.000000Z"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "data": {
                        "id": 0,
                        "name": "string",
                        "email": "string",
                        "last_login_at": "string",
                        "created_at": "string",
                        "updated_at": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "email",
                  "password",
                  "password_confirmation"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "name": "string",
                    "email": "string",
                    "password": "string",
                    "password_confirmation": "string"
                  }
                }
              }
            }
          },
          "description": ""
        }
      },
      "put": {
        "summary": "User Update",
        "operationId": "put-users-userId",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "last_login_at": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "data": {
                        "id": 0,
                        "name": "string",
                        "email": "string",
                        "last_login_at": "string",
                        "created_at": "string",
                        "updated_at": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "last_login_at": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "data": {
                        "id": 1,
                        "name": "Admin",
                        "email": "admin@admin.com",
                        "last_login_at": "2022-11-28 05:30:05",
                        "created_at": "2022-11-28T05:29:41.000000Z",
                        "updated_at": "2022-11-28T05:30:05.000000Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  }
                },
                "x-examples": {
                  "example-1": {
                    "name": "string",
                    "email": "string",
                    "password": "string",
                    "password_confirmation": "string"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "User Destroy",
        "operationId": "delete-users-userId",
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/documents": {
      "get": {
        "summary": "Document Index",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "content": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "links": {
                      "type": "object",
                      "properties": {
                        "first": {
                          "type": "string"
                        },
                        "last": {
                          "type": "string"
                        },
                        "prev": {
                          "type": "null"
                        },
                        "next": {
                          "type": "null"
                        }
                      }
                    },
                    "meta": {
                      "type": "object",
                      "properties": {
                        "current_page": {
                          "type": "integer"
                        },
                        "from": {
                          "type": "integer"
                        },
                        "last_page": {
                          "type": "integer"
                        },
                        "links": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "url": {
                                "type": [
                                  "null",
                                  "string"
                                ]
                              },
                              "label": {
                                "type": "string"
                              },
                              "active": {
                                "type": "boolean"
                              }
                            }
                          }
                        },
                        "path": {
                          "type": "string"
                        },
                        "per_page": {
                          "type": "integer"
                        },
                        "to": {
                          "type": "integer"
                        },
                        "total": {
                          "type": "integer"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "data": [
                        {
                          "id": 1,
                          "name": "teteweheheh",
                          "content": "tetewehehehtetewehehehtetewehehehtetewehehehteteweheheh",
                          "created_at": "2022-11-28T12:46:43.000000Z",
                          "updated_at": "2022-11-28T12:46:43.000000Z"
                        }
                      ],
                      "links": {
                        "first": "http://rimsys.test/api/users/me/documents?page=1",
                        "last": "http://rimsys.test/api/users/me/documents?page=1",
                        "prev": null,
                        "next": null
                      },
                      "meta": {
                        "current_page": 1,
                        "from": 1,
                        "last_page": 1,
                        "links": [
                          {
                            "url": null,
                            "label": "&laquo; Previous",
                            "active": false
                          },
                          {
                            "url": "http://rimsys.test/api/users/me/documents?page=1",
                            "label": "1",
                            "active": true
                          },
                          {
                            "url": null,
                            "label": "Next &raquo;",
                            "active": false
                          }
                        ],
                        "path": "http://rimsys.test/api/users/me/documents",
                        "per_page": 15,
                        "to": 1,
                        "total": 1
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-documebts"
      },
      "parameters": []
    },
    "/documents/{documentId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "minimum": 1,
            "example": 1,
            "exclusiveMinimum": true
          },
          "name": "documentId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Document Show",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "content": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "data": {
                        "id": 1,
                        "name": "teteweheheh",
                        "content": "tetewehehehtetewehehehtetewehehehtetewehehehteteweheheh",
                        "created_at": "2022-11-28T12:46:43.000000Z",
                        "updated_at": "2022-11-28T12:46:43.000000Z"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "data": {
                        "id": 0,
                        "name": "string",
                        "content": "string",
                        "created_at": "string",
                        "updated_at": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-documents-documentId"
      },
      "post": {
        "summary": "Document Store",
        "operationId": "post-documents-documentId",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "content": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "example-1": {
                  "value": {
                    "name": "string",
                    "content": "string"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Document Update",
        "operationId": "put-documents-documentId",
        "responses": {
          "200": {
            "description": "OK"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "content": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "data": {
                        "id": 2,
                        "name": "A document name",
                        "content": "some document content",
                        "created_at": "2022-11-28T12:50:19.000000Z",
                        "updated_at": "2022-11-28T12:50:19.000000Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "content": {
                    "type": "string"
                  }
                },
                "x-examples": {
                  "example-1": {
                    "name": "string",
                    "content": "string"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Document Destroy",
        "operationId": "delete-documents-documentId",
        "responses": {
          "204": {
            "description": "No Content"
          }
        },
        "description": ""
      }
    },
    "/users/{userId}/documents": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "minimum": 1,
            "exclusiveMinimum": true
          },
          "name": "userId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "User Document Index",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "content": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "links": {
                      "type": "object",
                      "properties": {
                        "first": {
                          "type": "string"
                        },
                        "last": {
                          "type": "string"
                        },
                        "prev": {
                          "type": "null"
                        },
                        "next": {
                          "type": "null"
                        }
                      }
                    },
                    "meta": {
                      "type": "object",
                      "properties": {
                        "current_page": {
                          "type": "integer"
                        },
                        "from": {
                          "type": "integer"
                        },
                        "last_page": {
                          "type": "integer"
                        },
                        "links": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "url": {
                                "type": [
                                  "null",
                                  "string"
                                ]
                              },
                              "label": {
                                "type": "string"
                              },
                              "active": {
                                "type": "boolean"
                              }
                            }
                          }
                        },
                        "path": {
                          "type": "string"
                        },
                        "per_page": {
                          "type": "integer"
                        },
                        "to": {
                          "type": "integer"
                        },
                        "total": {
                          "type": "integer"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "data": [
                        {
                          "id": 1,
                          "name": "teteweheheh",
                          "content": "tetewehehehtetewehehehtetewehehehtetewehehehteteweheheh",
                          "created_at": "2022-11-28T12:46:43.000000Z",
                          "updated_at": "2022-11-28T12:46:43.000000Z"
                        }
                      ],
                      "links": {
                        "first": "http://rimsys.test/api/users/me/documents?page=1",
                        "last": "http://rimsys.test/api/users/me/documents?page=1",
                        "prev": null,
                        "next": null
                      },
                      "meta": {
                        "current_page": 1,
                        "from": 1,
                        "last_page": 1,
                        "links": [
                          {
                            "url": null,
                            "label": "&laquo; Previous",
                            "active": false
                          },
                          {
                            "url": "http://rimsys.test/api/users/me/documents?page=1",
                            "label": "1",
                            "active": true
                          },
                          {
                            "url": null,
                            "label": "Next &raquo;",
                            "active": false
                          }
                        ],
                        "path": "http://rimsys.test/api/users/me/documents",
                        "per_page": 15,
                        "to": 1,
                        "total": 1
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-users-userId-documents"
      }
    },
    "/users/{userId}/documents/{documentId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "minimum": 1,
            "example": 1,
            "exclusiveMinimum": true
          },
          "name": "userId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "integer",
            "minimum": 1,
            "example": 1
          },
          "name": "documentId",
          "in": "path",
          "required": true
        }
      ],
      "put": {
        "summary": "User Document Associate",
        "operationId": "put-users-userId-documents-documentId",
        "responses": {
          "202": {
            "description": "Accepted"
          }
        }
      },
      "delete": {
        "summary": "User Document Disassociate",
        "operationId": "delete-users-userId-documents-documentId",
        "responses": {
          "204": {
            "description": "No Content"
          }
        },
        "description": ""
      }
    },
    "/auth": {
      "parameters": [],
      "post": {
        "summary": "Login/Generate Access Token",
        "operationId": "post-auth",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "x-examples": {
                  "example-1": {
                    "email": "string",
                    "password": "string"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Logout/Delete Token",
        "operationId": "delete-auth",
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {}
  }
}